name: Windows CMake

runs:
  using: composite

  steps:
    - name: Create build directory
      run: mkdir build
      shell: bash

    - name: Configure
      run: cmake -LA .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTS=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DBoost_USE_STATIC_LIBS=ON
      shell: bash
      working-directory: build

