name: CI

on: [ push, pull_request ]

jobs:

  ubuntu22-pg11-gcc10-jit:
    runs-on: ubuntu-22.04

    env:
      CC: gcc-10
      CXX: g++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 11
      POSTGIS_VERSION: 3
      BUILD_TYPE: Release
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu22-pg11-clang13-jit:
    runs-on: ubuntu-22.04

    env:
      CC: clang-13
      CXX: clang++-13
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 11
      POSTGIS_VERSION: 3
      BUILD_TYPE: Release
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu22-pg11-gcc10:
    runs-on: ubuntu-22.04

    env:
      CC: gcc-10
      CXX: g++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 11
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test


  ubuntu22-pg11-clang13:
    runs-on: ubuntu-22.04

    env:
      CC: clang-13
      CXX: clang++-13
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 11
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu22-pg13-gcc11-jit:
    runs-on: ubuntu-22.04

    env:
      CC: gcc-11
      CXX: g++-11
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 13
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test


  ubuntu22-pg12-clang14-jit:
    runs-on: ubuntu-22.04

    env:
      CC: clang-14
      CXX: clang++-14
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 12
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu22-pg12-clang15-noproj:
    runs-on: ubuntu-22.04

    env:
      CC: clang-15
      CXX: clang++-15
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 12
      POSTGIS_VERSION: 3
      WITH_PROJ: OFF
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu22-pg16-clang15:
    runs-on: ubuntu-22.04

    env:
      CC: clang-15
      CXX: clang++-15
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 16
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu22-pg13-gcc12-release:
    runs-on: ubuntu-22.04

    env:
      CC: gcc-12
      CXX: g++-12
      EXTRA_FLAGS: -Wno-stringop-overread
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 13
      POSTGIS_VERSION: 3
      BUILD_TYPE: Release
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg14-clang16-jit:
    runs-on: ubuntu-24.04

    env:
      CC: clang-16
      CXX: clang++-16
      LUA_VERSION: 5.4
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 14
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg14-clang17-proj:
    runs-on: ubuntu-24.04

    env:
      CC: clang-17
      CXX: clang++-17
      LUA_VERSION: 5.4
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 14
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg15-clang17-noproj:
    runs-on: ubuntu-24.04

    env:
      CC: clang-17
      CXX: clang++-17
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 15
      POSTGIS_VERSION: 3
      WITH_PROJ: OFF
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg15-clang18:
    runs-on: ubuntu-24.04

    env:
      CC: clang-18
      CXX: clang++-18
      LUA_VERSION: 5.4
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 15
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg16-gcc12-release:
    runs-on: ubuntu-24.04

    env:
      CC: gcc-12
      CXX: g++-12
      EXTRA_FLAGS: -Wno-stringop-overread
      LUA_VERSION: 5.4
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 16
      POSTGIS_VERSION: 3
      BUILD_TYPE: Release
      PSYCOPG: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg17-clang16-cpp20:
    runs-on: ubuntu-24.04

    env:
      CC: clang-16
      CXX: clang++-16
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 17
      POSTGIS_VERSION: 3
      CPP_VERSION: 20
      BUILD_TYPE: Debug
      PSYCOPG: 3

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg17-clang16-san:
    runs-on: ubuntu-24.04

    env:
      CC: clang-16
      CXX: clang++-16
      EXTRA_FLAGS: -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer
      LDFLAGS: -fsanitize=address,undefined
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 17
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 3

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  ubuntu24-pg17-gcc12-cpp20:
    runs-on: ubuntu-24.04

    env:
      CC: gcc-12
      CXX: g++-12
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 17
      POSTGIS_VERSION: 3
      CPP_VERSION: 20
      BUILD_TYPE: Debug
      PSYCOPG: 3

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/build-and-test

  windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
    runs-on: ${{ matrix.os }}

    env:
      VCPKG_DEFAULT_BINARY_CACHE: C:/vcpkg_binary_cache

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            C:/vcpkg_binary_cache
          key: vcpkg-binary-cache-${{ matrix.os }}-${{ github.run_id }}
          restore-keys: |
            vcpkg-binary-cache-${{ matrix.os }}
      - name: Prepare cache
        run: if [ ! -d C:/vcpkg_binary_cache ]; then mkdir C:/vcpkg_binary_cache; fi
        shell: bash
      - uses: ./.github/actions/win-postgres
      - uses: ./.github/actions/win-install
      - uses: ./.github/actions/win-cmake
      - uses: ./.github/actions/win-build
      - uses: ./.github/actions/win-test
      - name: Package osm2pgsql
        run: |
          mkdir c:/artifact/
          mkdir c:/artifact/osm2pgsql-bin
          cp -r Release/* ../README.md ../COPYING ../*.style ../scripts ../flex-config c:/vcpkg/installed/x64-windows/share/proj/proj.db c:/artifact/osm2pgsql-bin/
        shell: bash
        working-directory: build
        if: matrix.os == 'windows-2025'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: osm2pgsql-win64
          path: c:/artifact
        if: matrix.os == 'windows-2025'

  windows-package:
    needs: windows
    runs-on: windows-2025

    env:
      OSMURL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: osm2pgsql-win64
      - uses: ./.github/actions/win-postgres
      - name: Set up database
        run: |
          & $env:PGBIN\createdb osm
          & $env:PGBIN\psql -d osm -c "CREATE EXTENSION hstore; CREATE EXTENSION postgis;"
        shell: pwsh
      - name: Get test data
        run: Invoke-WebRequest -Uri $env:OSMURL -OutFile "testfile.osm.pbf"
        shell: pwsh
      - name: Execute osm2pgsql
        run: ./osm2pgsql-bin/osm2pgsql --slim -d osm testfile.osm.pbf
        shell: bash

